version: '3.8'
services:

  postgres-service:
    container_name: postgres-service
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webflux-demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  oauth-mock-server:
    container_name: mock-oauth2-server
    image: ghcr.io/navikt/mock-oauth2-server:2.1.8
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./mock-oauth2-server/config.json:/app/config.json
    environment:
      JSON_CONFIG_PATH: /app/config.json
