### Get a Post by Id without comments
GET {{serviceHost}}/post/{{postId1}}/without-comments
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### Get a Post by Id with comments flatMapping
GET {{serviceHost}}/post/{{postId1}}/with-comments-flatMapping
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### Get a Post by Id with comments zipping
GET {{serviceHost}}/post/{{postId1}}/with-comments-zipping
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### Get a Post by Id with comments zipping and is beautiful
GET {{serviceHost}}/post/{{postId1}}/with-comments-zipping-and-is-beautiful
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### Add a Post
POST {{serviceHost}}/post/add
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "content": "My post",
  "tags": [
    "TAG"
  ]
}

### Update a Post
PUT {{serviceHost}}/post/update/{{postId11}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "id": "{{postId1}}",
  "content": "My post updated",
  "tags": [
    "UPDATED_TAG"
  ]
}

### Delete a Post
DELETE {{serviceHost}}/post/delete/{{postId1}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### Get all Posts by UserId using flux filters
POST {{serviceHost}}/post/all
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "tags": ["UPDATED_TAG"]
}

### Get all Posts by UserId using custom query
POST {{serviceHost}}/post/all/with-custom-query
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "tags": ["UPDATED_TAG"]
}
