common:
  jwt:
    baseUri: http://localhost:8081
  isBeautifulSerer:
    baseUri: http://localhost:8082
  db:
    config:
      auth: &common-db-config-auth
        user: root
        password: root
      url: postgresql://localhost:5432/webflux-demo

logging:
  level:
    org.springframework: INFO
    io.r2dbc.postgresql.QUERY: INFO

spring:
  flyway:
    url: jdbc:${common.db.config.url}
    locations: classpath:db/migration
    <<: *common-db-config-auth
  r2dbc:
    url: r2dbc:${common.db.config.url}
    username: ${common.db.config.auth.user}
    password: ${common.db.config.auth.password}
  application:
    name: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${common.jwt.baseUri}/mocked
          jwk-set-uri: ${common.jwt.baseUri}/mocked/jwks
          jws-algorithms: ES384

isBeautifulServer:
  base-endpoint: ${common.isBeautifulSerer.baseUri}
  is-beautiful-path: /is-beautiful
